# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 830f5780b6145f5add010f818fdbc607232e6a8605ca5e1ee45d01165dac62a6ee8be0a16790bd80d8e2c2e24dc3ff69c87eb20405c85ac27a876cf526ea0623

test:
  secret_key_base: 35afaf204c8e246acc70f5299b914caf4a9a99030776c8d8aaf3c5d139c2ed664133526bf248b68d380ce4ba77e0102758b73370e14f7e3cdbead7375f5565c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
